name: Deploy-static-site-to-Azure

on:
  push:
    branches: [ main ]          
  workflow_dispatch:            

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to $web container
      run: |
        az storage blob upload-batch \
          --destination "\$web" \
          --account-name ${{ secrets.STORAGE_ACCOUNT }} \
          --source . \
          --overwrite \
          --auth-mode login         


    - name: Done
      run: echo "Site uploaded – visit the static URL to verify."
